data:
  yaml:
    write:
      line_width: -1
search:
  paths:
    - app/
    - lib/
ignore_unused:
  - 'components.accordion.*'
  - 'components.related_footer_navigation.*'
  - 'components.related_navigation.*'
