on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  visual-regression-test-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # Also runs `bundle install`
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: "12"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - uses: percy/exec-action@v0.3.1
        with:
          command: bundle exec rspec --tag visual_regression
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
